exclude: [assets/less, docker]

paginate: 10
paginate_path: "/page:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Mark Siebert"

domain: "https://msiebert.github.io/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
